### ISSUE TITLE
[WIP] OG Combat Milestones

### ISSUE THREAD

**Issue by uwadmin12** [seedhartha/reone#21]
# Combat Milestones

This issue is opened to track the progress of combat implementation, in addition to RoadMap. Any comment/suggestions for modification is appreciated.

Stage 1 and 2 are most relevant to Release 0.11.0.

## Stage 1: Framework Setup

- [x] Restructure AttackAction cycle (locate target -> queue -> completion)
- [x] Creature faction and hostility check
- [x] Scanning area for hostiles and add those to combatant list
- [x] Equipment Swapping Commands
- [x] Crack the combat animation code (match animation to current equipment)
- [x] **Combat Mode toggle**
- [x] Combat-mode default animation
- [x] Combat-mode camera angle
- [ ] Pausing
- [x] Use deactivation timer (10 second timeout for inactivity)
- [x] Use ai timer (3 second for each creature/rotate per frame)???
- [ ] Implement script functions for GetIsEnemy and SetFaction, etc.

## Stage 2: GUI and Functional Logic

- [x] \[D20\] OG Combat GUI: action bar, action queue
- [ ] GUI: health bar
- [ ] \[D20\] OG GUI: action slots
- [ ] Feedback text, animated text (damage)
- [ ] Death, run onDeath script (loot drop), and update combat data structures (test with instaKill)
- [ ] Item Consumption Commands
- [ ] Force Power implementation
- [ ] \[D20\] OG Combat GUI: fill in item icons (e.g. icons for all types of attacks, powers)
- [ ] Blaster visual effect and hit/miss logic.
- [ ] Damage/effect logic (need to consider creature stats, feat, and effects)
- [ ] (TBD) Togglable feature: invoke k_ai_master
- [ ] (TBD) Feat and Skills?
- [ ] (TBD) AI Optimization: Keep track of last known position of hostile on deactivation timer start (for realism)

## Stage 3: Polishing and Completeness

- [ ] Integrate visual effect for all types of attack
- [ ] OG Feat complete implementation
- [ ] OG Skills complete implementation
- [ ] AI Optimization: Max Damage Output, Max Buff onEnterCombat
- [ ] AI Optimization: Item Consumption for survival
- [ ] Collision Improvement: Colliding with movable objects will move them a little (might need a rudimentary physics engine)
- [ ] Collision Improvement: Colliding with objects will permit slower movement in conflict-less direction
- [ ] Collision Improvement: Collision trap solutions (i.e. a bug where the AABB box of two objects accidentally intersect, and as a result the objects are trapped and cannot move in any directions)
- [ ] Collision Improvement: AI adjustment, if someone is too close, back up a little, or move somewhere else. (Remember the Telos duel where you could "push" the sisters out of bound)
